# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:
  # legacy compilers for things that refuse to move
  # modern compilers
  - gcc                        # [linux64]
  - vs2022                     # [win]
  - clang                      # [osx]
c_compiler_version:            # [unix]
  - 9                          # [linux64]
  - 4                          # [osx]
cxx_compiler:
  # modern compilers
  - gxx                        # [linux64]
  - clangxx                    # [osx]
  - vs2022                     # [win]
cxx_compiler_version:          # [unix]
  - 9                          # [linux64]
  - 4                          # [osx]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [(linux64 or osx)]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 9                          # [linux64]
  - 5                          # [win64]
  - 4                          # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]
CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

build:
  skip: true # [win32]

# dual build configuration
channel_sources:
  - conda-forge,defaults                        # [not aarch64]

channel_targets:
  - conda-forge main

extend_keys:
  - extend_keys
  - ignore_build_only_deps
  - ignore_version
  - pin_run_as_build

ignore_build_only_deps:
  - numpy
  - python


# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  eigen:
    max_pin: x.x.x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gsl:
    max_pin: x.x
  gdal:
    max_pin: x.x
  gdk_pixbuf:
    max_pin: x.x.x
  geos:
    max_pin: x.x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  icu:
    max_pin: x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg-turbo:
    min_pin: x.x
    max_pin: x
  json-c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libdap4:
    max_pin: x.x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libmatio:
    max_pin: x.x
  libnetcdf:
    max_pin: x.x.x
  libpcap:
    max_pin: x.x
  libpng:
    max_pin: x.x
  libprotobuf:
    max_pin: x.x
  librdkafka:
    max_pin: x.x.x
  librsvg:
    max_pin: x.x
  libspatialindex:
    max_pin: x.x
  libssh2:
    max_pin: x.x
  libsvm:
    max_pin: x.x
  libunwind:
    max_pin: x.x
  libtiff:
    max_pin: x
  libwebp:
    max_pin: x.x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf-cxx4:
    max_pin: x.x
  netcdf-fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  openblas:
    max_pin: x.x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  pixman:
    max_pin: x.x
  poppler:
    max_pin: x.x
  proj4:
    max_pin: x.x.x
  pyqt:
    max_pin: x.x
  qt:
    max_pin: x.x
  readline:
    max_pin: x
  r-base:
    max_pin: x.x.x
  snappy:
    max_pin: x.x.x
  sox:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  sundials:
    max_pin: x.x
  tk:
    max_pin: x.x
  vc:
    max_pin: x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xerces-c:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x

libblas: 3.9.0 *netlib
libcblas: 3.9.0 *netlib
liblapack: 3.9.0 *netlib
liblapacke: 3.9.0 *netlib
python: 3.8.* *_cpython
eigen: 3.4.0 *

# vs2017_win_64:
#   - 19.15.26726 h3c6f0ee_0  # [win-64]

