{% set version = "2.10.3" %}

package:
  name: cbc
  version: {{ version }}

source:
  - url: https://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
    fn: {{ version }}.tgz
    sha256: ad388357129497c1cc3be50c3707b1995fddf0a4188abc8e3669173f0179ecff

build:
  number: 1002
  skip: true # [not win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - zlib
    - bzip2

  run:
    - libblas
    - libcblas
    - liblapack
    - zlib
    - bzip2

about:
  home: https://projects.coin-or.org/Cbc
  license: Eclipse Public License (EPL)
  license_file: LICENSE
  summary: COIN-OR Branch-and-Cut solver.

extra:
  recipe-maintainers:
    - saedrna
