{% set version = "6.1.4" %}

package:
  name: qwt
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/qwt/files/qwt/{{ version }}/qwt-{{ version }}.tar.bz2
  sha256: 1529215329e51fc562e0009505a838f427919a18b362afff441f035b2d9b5bd9
  patches:
    # Can't seem to avoid /usr/local/ install without patch
    - qwtconfig.pri.patch
    # build in release mode
    - windows.patch
    - no-framework.patch

build:
  skip: True  # [win and vc<14]
  number: 1004

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libXau') }}  # [linux]

  host:
    - qt5-base
    - qt5-declarative
    - qt5-svg
    - qt5-tools
  run:
    - qt5-base
    - qt5-declarative
    - qt5-svg
    - qt5-tools
    
about:
  home: http://qwt.sourceforge.net/ 
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Qt widgets for technical applications
  doc_url: http://qwt.sourceforge.net/
  dev_url: https://sourceforge.net/projects/qwt/

extra:
  recipe-maintainers:
    - ceholden
    - jschueller
    - marcelotrevisani
    - saedrna
